### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by SashaSavin** [Poklok/tg_api_bot#1]
1. Давайте создадим ветку dev и продолжим работать в ней.
2. В гитигнор стоит занести .idea, __pycache__ папки, они не нужны в репозитории (напомните на занятии, я покажу, как убрать в гитхабе) 
3.  [create api in project] - некорректное название коммита, может ввести в заблуждение. Мы не создаем апи в проекте, а используем собственный апи. Корректнее было бы назвать - use own api in project или что-то в этом духе.

**Comment by Poklok** [comment]
Большое спасибо, всё исправил.
